export const galleryData = [
    { image: "../../assets/bedroom_1_alt.jpg" },
    { image: "../../assets/bedroom_1_beds.jpg" },
    { image: "../../assets/bedroom_2_beds.jpg" },
    { image: "../../assets/front_daytime.jpg" },
    { image: "../../assets/front_nighttime.jpg" },
    { image: "../../assets/guest_bathroom.jpg" },
    { image: "../../assets/kitchen_appliances.jpg" },
    { image: "../../assets/kitchen_bar_2.jpg" },
    { image: "../../assets/kitchen_bar.jpg" },
    { image: "../../assets/kitchen.jpg" },
    { image: "../../assets/laundry_room.jpg" },
    { image: "../../assets/living_room_1.jpg" },
    { image: "../../assets/living_room_2.jpg" },
    { image: "../../assets/master_bedroom.jpg" },
    { image: "../../assets/master_bathroom_2.jpg" },
    { image: "../../assets/pool_daytime.jpg" },
    { image: "../../assets/pool_nighttime.jpg" },
    { image: "../../assets/pool_seating.jpg" },
];
